rom_path = "roms/"
core_path = "cores/"
cache_path = "cache/"

# The systems to be configured
system = [
	{ name = "NES", lib = "FCEUmm", ext = ["nes"] },
	{ name = "SNES", lib = "Snes9x 2010", ext = ["sfc"] },
	{ name = "PSX", lib = "Beetle PSX", ext = ["cue"] },
	{ name = "MD", lib = "Genesis Plus GX", ext = ["md"] },
	{ name = "DOOM", lib = "PrBoom", ext = ["wad"] },
	#{ name = "N64", lib = "ParaLLEl N64", ext = ["z64"]  },
	#{ name = "PS2", lib = "pcsx2 (alpha)", ext = ["iso"]  },
	#{ name = "NDS", lib = "melonDS", ext = ["nds"]  },
	#{ name = "3DS", lib = "Citra", ext = ["3ds"]  },
]

[menu]
max_tile_size = 200
poweroff_cmd = "sudo systemctl poweroff"
reboot_cmd = "sudo systemctl reboot"
